### ISSUE TITLE
FreeBSD support needed

### ISSUE THREAD

**Issue by jungle-boogie** [harelba/q#101]
1. I modified to q file to point to python3. Is that bad?

2. Doesn't work on freeBSD:

````./q
  File "./q", line 105
    print sql, " params: " + str(params)
            ^
SyntaxError: invalid syntax````

**Comment by kAlmAcetA** [comment]
only python 2.x > http://harelba.github.io/q/requirements.html

**Comment by harelba** [comment]
Hi @jungle-boogie , sorry for the late reply,

only python 2 is supported for now. I haven't checked how far the incompatibility goes, perhaps I'll be able to take a look before releasing the next version, and see if I can make it compatible with python 3 without breaking stuff.

Harel

**Comment by jungle-boogie** [comment]
Hello,

Using the single file, I'm able to use the cool script. I'd rather you focus on improving what you know rather than checking incompatibilities. ;)

Thanks!
