### ISSUE TITLE
Add support for universal newlines while parsing

### ISSUE THREAD

**Issue by harelba** [harelba/q#104]

**Comment by alexmhurst** [comment]
I believe this is fixed in my PR: https://github.com/harelba/q/pull/110

**Comment by harelba** [comment]
Added flag for universal newline support (currently only for regular files, not supporting .gz or direct-stdout). It's not in the new released version, but it's in master. Glad if people could give it a go before I issue a new version.

**Comment by harelba** [comment]
fully supported for both python 2 and 3 as part of 2.0.19.
