### ISSUE TITLE
file parameter wrong

### ISSUE THREAD

**Issue by jungle-boogie** [harelba/q#106]
Hello,

    q
    q version 1.5.0
    Must provide at least one query in the command line, or through a file with the -f parameter

Notice that it says -f

But passing this `q -H -d, -f test` doesn't return what we need.

This website: http://harelba.github.io/q/ reports we actually want to use `-q test`

https://harelba.github.io/q/usage.html

    -q QUERY_FILENAME, --query-filename=QUERY_FILENAME
                        Read query from the provided filename instead of the
                        command line, possibly using the provided query
                        encoding (using -Q).

That works and gives me desired results!

**Comment by harelba** [comment]
fixed on master.

Will close it when the new version is released.

Thanks a lot @jungle-boogie for finding and help with this!

**Comment by jungle-boogie** [comment]
Hi @harelba,

Thank you for correcting!
