### ISSUE TITLE
Improper double-quote escaping in output

### ISSUE THREAD

**Issue by mikaelgrave** [harelba/q#115]
My input is CSV, with some fields containing double-quotes. See below:

[foo.csv](https://github.com/harelba/q/files/51348/foo.txt)

I run the following command:

`q -H -O -d , -W all 'select * from foo.csv'`

Here is the output:

[out.csv](https://github.com/harelba/q/files/51352/out.txt)

As you can see, the email address on row #2 is improperly escaped:

`"Male","Tom Gray"@mylobbylink.com"","CEO"`

That results into further processing of the output into most spreadsheet app or CSv processing apps, to fail and not properly load that row.

Proper escaping would be:

`"Male","Tom Gray""@mylobbylink.com""","CEO"`

(Note: You may wonder why an email address contains double-quotes -- that's a good question, and it's indeed an invalid address but it's not the point)

I was looking for command line options to set the escaping mode, but there is no such option.

Thanks for your help!

**Comment by harelba** [comment]
@mikaelgrave Hi, sorry for the late reply, I'm out on vacation.

I'll take a deeper look and update here.

Harel

**Comment by harelba** [comment]
@mikaelgrave Indeed an important bug, thanks a lot! 

Fixed it, but the issue implicates a bug in one of the tests as well (meaning that the change will break current behaviour), so I wanna test it some more before checking it in.

If you're not on Windows and want the un-checkedin version, ping me over email harelba@gmail.com and I'll be glad to send it to you in the mean time.

Harel

**Comment by harelba** [comment]
btw, if there's anyone who would be kind enough to test the modified version on their stuff, just to make sure that nothing important is broken, I'd be glad to provide it.

**Comment by mikaelgrave** [comment]
@harelba Thanks a lot! I'll gladly test it. I've just emailed you.

**Comment by harelba** [comment]
@mikaelgrave - Sent over email. Thanks a lot!

**Comment by harelba** [comment]
Fix integrated into master.

Thanks @mikaelgrave for finding the problem and helping to test the fix!

**Comment by mikaelgrave** [comment]
Thanks @harelba for fixing this so quickly.

**Comment by harelba** [comment]
Fixed in v1.6.3.
