### ISSUE TITLE
Continue if there's empty data file in a batch

### ISSUE THREAD

**Issue by nduc** [harelba/q#122]
q -H -d , "select \* from *.csv"
If there is a file with only header and no data, the process failed with "Warning - data is empty"

**Comment by harelba** [comment]
This indeed seems like a bug, since it's only meant to be a warning thrown to stderr, and not fail anything.

I'll dig into it.

Thanks a lot @nduc !

**Comment by harelba** [comment]
Fixed in master. Will go out as part of the next version. 

@nduc I'd appreciate it if you could download the master version and check that it works for your use case. Please send me information here or through email if there are still any issues.

btw, it turns out that this exposes another issue in which q was not issuing an error even if the file was completely empty (e.g. the actual header is missing but expected). Fixed that as well, but it's kind of a breaking change, meaning that there might be people out there that relied on the broken behaviour.

Sorry for the inconvenience.

Harel

**Comment by harelba** [comment]
Reopened until it will go out in the next official version (Didn't mean to close it - the checkin did that automatically).

**Comment by nduc** [comment]
@harelba I've rebuild and tried running it but I'm getting an error
λ q -H -d , "select * from *.csv"
Traceback (most recent call last):
  File "<string>", line 53, in <module>
TypeError: limit must be an integer
q returned -1

Am I missing a library?

**Comment by harelba** [comment]
It seems related to the python version you're using. q requires python 2.6+

Can you check the python version you running? 

btw - Which OS are you running on?

**Comment by harelba** [comment]
also - python 3 is not supported yet, perhaps it might be related as well.

**Comment by nduc** [comment]
I am using Python 2.7.11 on Windows 10
λ python --version
Python 2.7.11

**Comment by harelba** [comment]
Interesting - Is it a 64 bit system? 

Also, please tell me what do you mean "rebuild" q? How do you run it?

Run python REPL, and inside it run:
```
import sys
print sys.maxsize
````

I suspect it might be related to the fact that it's a 64 bit installation (When I provide q.exe on windows, it's compiled with the python 32 bit binaries, regardless of the target OS 32/64 bit configuration).

Several options:
1. Hack the q python code (and hope that it's the only incompatibility) - Change line 53 "sys.maxsize" to 131072 and try to run it.
2. Download a side-version of python 2.7 32bit, extract it to a separate folder, and run q with that python (don't override the system python or anything, just run python using the full path of this extracted folder)
3. Wait for the next official version (in which I provide a full-blown q.exe file).

Sorry for the inconvenience. Wish I could provide you with a better experience.
Harel

**Comment by nduc** [comment]
Harel, please, you have saved me many hours already.  It's the least I can do.
I am on Windows 10 64 bit Home edition.
By rebuild, I mean I followed the instruction in Create Windows Setup Instruction in the dist folder.

I've replace sys.maxsize with 131072 and I got an error
λ q -H -d , "select * from *.csv"
query error: table temp_table_10001 has no column named c1

Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print sys.maxsize
9223372036854775807

And there's the problem.  I am using Python 2.7.11 64-bit!

I tried it with 32-bit version
λ python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print sys.maxsize
2147483647

but I'm still getting error when I build
λ python c:\q-build-environment\PyInstaller-3.1.1\pyinstaller.py -F --distpath=win_output --workpath=win_build c:\q
\bin\q
Traceback (most recent call last):
  File "c:\q-build-environment\PyInstaller-3.1.1\pyinstaller.py", line 14, in <module>
    from PyInstaller.__main__ import run
  File "c:\q-build-environment\PyInstaller-3.1.1\PyInstaller\__main__.py", line 21, in <module>
    import PyInstaller.building.build_main
  File "c:\q-build-environment\PyInstaller-3.1.1\PyInstaller\building\build_main.py", line 32, in <module>
    from ..depend import bindepend
  File "c:\q-build-environment\PyInstaller-3.1.1\PyInstaller\depend\bindepend.py", line 42, in <module>
    from ..utils.win32.winmanifest import RT_MANIFEST
  File "c:\q-build-environment\PyInstaller-3.1.1\PyInstaller\utils\win32\winmanifest.py", line 97, in <module>
    from PyInstaller.utils.win32 import winresource
  File "c:\q-build-environment\PyInstaller-3.1.1\PyInstaller\utils\win32\winresource.py", line 20, in <module>
    import pywintypes
ImportError: No module named pywintypes

I'm sorry if I'm wasting your time.  I really appreciate your efforts!

**Comment by nduc** [comment]
I started from scratch and made sure all my installs were 32 bit and I get a different error now.
λ q -H -d , "select * from *.csv"
query error: table temp_table_10001 has no column named c1

**Comment by harelba** [comment]
Hi, thanks a lot for the input. 

I'll be near my computer tomorrow morning Israel time, and take a deeper look. 

I suspect that these issue is addressed through the vagrant instance that I'm using in order to create the build.

**Comment by harelba** [comment]
Btw, I have an idea that it might be related to a small issue in the fix I introduced today... As I mentioned, I'll take a look at it first thing in the morning. 

Harel

**Comment by harelba** [comment]
Sorry for the late reply.

It seems like a deeper thing, I'll have to continue my investigation. Sorry for the inconvenience

Harel

**Comment by harelba** [comment]
Original issue fixed in v1.6.3.
