### ISSUE TITLE
Multiple files in FROM-clause

### ISSUE THREAD

**Issue by schlauergerd** [harelba/q#123]
The following two commands work:
- `q "select * from file1 f"`
- `q "select * from file1 f join file2 g"`

But the command `q "select * from file1 f, file2 g"` produces an error: `query error: no such table: file2`

If the second file/table is in an other directory, I get a syntax error. `q "select * from file1 f, dir/file2 g"` produces `query error: near "/": syntax error`

**Comment by harelba** [comment]
Hi @schlauergerd , sorry for the late reply.

q follows the sqlite syntax, which does not support short-from joins. The way to write it is using the "cross join":

````
q "select * from file1 f cross join file2 g"
````

Please tell me if you still have any issues.

Harel

**Comment by schlauergerd** [comment]
Joins work as they should, so this issue can be closed.

Thanks

**Comment by harelba** [comment]
Thanks @schlauergerd !
