### ISSUE TITLE
randomly sample 100 rows

### ISSUE THREAD

**Issue by dclong** [harelba/q#125]
Can q randomly sample rows/records? If so, what's the syntax like?

**Comment by harelba** [comment]
the syntax is matching sqlite, so you can do the following in order to get random records. Take into account that this is not a light operation if dealing with very large files.

```seq 1 1000000 | q "select * from - order by random() limit 5"```

Don't hesitate to contact me if you need more assistance.

Harel

**Comment by bitti** [comment]
If you don't care (or know) about the exact number and just want to have a certain fraction you also could do something like this (here with a sample rate of about 1%):

    seq 1 1000000 | q "select * from - where random() % 100 = 0"

That's also slightly faster in my measurements.

**Comment by dclong** [comment]
Thank you, Harel and David! This is very helpful!
