### ISSUE TITLE
Unions

### ISSUE THREAD

**Issue by swsien127** [harelba/q#133]
Hi, just a quick question on whether q can support union clauses.

**Comment by harelba** [comment]
Hi @swsien127 

Yes, q supports unions. In general, all sqlite3 constructs are supported. See example below:

```
$ cat a.data
1 2 3
4 5 6
7 8 9
$ cat b.data
10 20 30
40 50 60
70 80 90
$ q "select * from a.data a where a.c1 = 1 union select * from b.data b where b.c3 = 90"
1 2 3
70 80 90
$
```
