### ISSUE TITLE
feature request: make `FROM -` optional when stdin is not a tty

### ISSUE THREAD

**Issue by sweentown** [harelba/q#139]
Excellent tool!  If I can make one suggestion, please make the `FROM -` optional when reading from standard input and the stdin is not a tty.  For example:

```
$ ps -ef | q -H 'SELECT `PID`, `PPID` FROM -'
```

It should be obvious from context, since you are piping data into stdin, that the data is coming from the standard input.  Even though it's only 7 extra characters it feels unnecessary

**Comment by serima** [comment]
I understand what you want to say, but in SQL, SELECT and FROM are always paired.
If q is designed based on sql, `FROM -` seems to be essential.

**Comment by harelba** [comment]
Thanks for the proposal @sweentown . However, I tend to agree with @serima that the pairing is better, and the cost of it is minimal. This might lead to complications in more complex queries, such as when joining stdin with some other table, and would require "tricks" in order to do right. The cost of optimizing for the simplest case is relatively high vs the benefits in my view.

**Comment by sweentown** [comment]
@serima I wasn't aware that FROM was required in SQL.  MySQL grammar, for example, specifies that the FROM clause is optional:

https://dev.mysql.com/doc/refman/5.5/en/select.html

```
SELECT
    ....
    select_expr [, select_expr ...]
    [FROM table_references <-- the square brackets here indicate that the from clause is optional
   ...
```

@harelba I frequently use `q` with simple queries from piped data, but I have not tried to do a join on stdin.  I tried to do a simple example and I can't even get join on stdin to work:

```
$ <data q 'select * from - join -'
query error: ambiguous column name: main.temp_table_10001.c1
$ <data q 'select main.temp_table_10001.c1 from - join -'
query error: ambiguous column name: main.temp_table_10001.c1
```

I'd be genuinely surprised if a complex join against stdin is more common than simple queries.  But as it is your project, it is your decision :)

**Comment by serima** [comment]
@sweentown Thank you for your advice. Certainly, if we do not refer to the table, FROM is optional.

**Comment by bitti** [comment]
@sweentown: If you really want to join stdin with itself you need to alias it, e.g.

    select * from - join - x

But I think @harelba was referring to the more common case of joining stdin with another file.

If using simple selects on stdin is a common usecase for you, you can define a simple script or bash function like this:

    qq() { q ${@:1:$#-1} "select ${!#} from -"; }

As bonus this example also allows you to drop the `select ` prefix.

@sweentown: Sure, but if you leave out `from` that also doesn't imply stdin as table but simply no table at all. That can be useful for queries like `select date()` (or just to test some sqlite functions) and is already working fine in `q`. So trying to imply stdin here would change that semantic and would contradict the SQL standard.

**Comment by bitti** [comment]
@sweentown: In fact the argument should be the other way around: if leaving out "from" would *not* be part of the SQL standard, we could think about giving it a special interpretation since there should be no conflict with existing usage (except that some might rely on it to fail).

**Comment by harelba** [comment]
Hi all, thank you for caring and for the discussion :)

My view on this is that it might be a nice convenience feature, but the fact that it kind of conflicts with a regular SQL semantics in which no-FROM means no-table, then I believe that the value it will be provide is not high enough to implement.

Harel
