### ISSUE TITLE
Warning....

### ISSUE THREAD

**Issue by Suleman-Elahi** [harelba/q#165]
![image](https://user-images.githubusercontent.com/24384996/37552840-cbdb790c-2979-11e8-8d82-9d79119aeabc.png)

What is this warning and how to fix it.????

**Comment by harelba** [comment]
Hi sorry for the late reply, and for the inconvenience... 

I'm aware of this error, it's caused by a bug in the tool that packages q into a windows executable. I need to issue a new version work around that bug. This will happen in the next two weeks

**Comment by harelba** [comment]
Hi, I've released a new version for windows 1.7.4 which solves this extra warning issue. Just download the new windows version from the site (remember to refresh the page properly, so the new link will be used) and install it. The setup version should be setup-1.7.4.exe.

**Comment by Suleman-Elahi** [comment]
Thanks...!!!
