### ISSUE TITLE
Ability to change delimiter in output?

### ISSUE THREAD

**Issue by jgclark** [harelba/q#176]
For a set of simple queries I just want to be able to output a list of names. I can do this easily enough using `SELECT ... firstname, lastname ... ` from my data, but it produces output with comma between the two fields (e.g. `Joe,Bloggs`). I was hoping to be able to set the delimiter to a space, using the SQL construct `SELECT ... firstname, lastname ...  FIELDS TERMINATED BY ' '`. This doesn't seem to be supported. Is there another method in q that would work instead, or do I need to do post-processing? Thanks.

**Comment by harelba** [comment]
q has an output delimiter parameter that you can use (`-D`). Run `q --help` for details if needed. 

btw, you could also control output for this specific case by using SQL string concatenation (e.g. `q "SELECT firstname||' '||lastname from ...."`). see sqlite's string concatenation info.
