### ISSUE TITLE
No output on windows 8.1 64 bit pro version 1.7.4

### ISSUE THREAD

**Issue by captlid** [harelba/q#177]
![screenshot 208](https://user-images.githubusercontent.com/10800350/46629983-bfa55980-cb10-11e8-9eaa-2e403be1ac49.png)

The file is a tab delimited file, but I am not getting any output as shown in the picture above.

**Comment by bitti** [comment]
Don't use single quotes to reference columns or you just get literal strings. Just leave the quotes off or use backticks instead if you have column names with special characters. Also see https://www.sqlite.org/lang.html

**Comment by captlid** [comment]
![screenshot 212](https://user-images.githubusercontent.com/10800350/46641266-ad421480-cb3e-11e8-84b4-75e2af948916.png)

still getting the same problem. The file is tab delimited. I have sqlite on my computer at home the queries work fine on the same imported file.

**Comment by harelba** [comment]
In order for q to use the header for the column names, you need to specify `-H` in the command line: `q -H "select ...."`

**Comment by captlid** [comment]
and apparently the delimiter too .
q -H -d, "select ...."
or 
q -H -t "select ...."

It works now. Without the delimiter specified it says no columns.
