### ISSUE TITLE
Feature: would be nice to specify header and format per-file

### ISSUE THREAD

**Issue by wtanksleyjr** [harelba/q#203]
I'm doing a lot of joins, and I find that I have to add and remove headers all the time. It would be cool to have some markup or options to allow that to be specified per-file, perhaps by defining tables in an option (which would also make it easier to specify filenames without running into SQL syntax problems). So for example:

`q -f a=~/author.tsv,Ht b=editor.tsv,t "select b.c1,a.name,b.c2 from a join b on a.ID=b.c1"`

**Comment by bitti** [comment]
That doesn't seem like anything you can already do with the shell. E.g. taking your example

    a=~/author.tsv b=<(cat dummy-header.tsv editor.tsv); q -H -t "select b.c1,a.name,b.c2 from $a a join $b b on a.ID=b.c1"

The `dummy-header.tsv` could contain a single line like `c1\tc2\tc3\t[...]` so you could "normalize" your files to contain all headers. Similarly, you can pipe through `tr` or something to normalize to tab if you have a different delimiter. Even if you worry about problematic filenames but you don't need a normalization you can still use the `<(...)` syntax to create an anonymous pipe (e.g. `a=<(cat ~/author.tsv)`), this gives unproblematic filenames like `/dev/fd/63`.

**Comment by wtanksleyjr** [comment]
Thank you for the tips; especially putting the named pipe into an environment variable is the syntax I needed. I'll close this issue -- if your idea is to keep the command line simpler I agree :) .

**Comment by bitti** [comment]
@wtanksleyjr: I'm not the author of `q`, so it's not for me to decide if this gets implemented. But the idea is stated in his Unix philosophy [rationale](https://github.com/harelba/q/blob/master/doc/RATIONALE.markdown#philosophy): just do one thing but try to do it well and for everything else rely on the power the combination of Unix tools gives you.

**Comment by wtanksleyjr** [comment]
Has anyone gotten the "b=<(cat blah); q ..." syntax to work? When I try it, the file's already gone. It seems the named pipe is deleted as soon as the command it's contained by ends (with the semicolon).

Is this only valid on some systems, like BSD/MacOS? I'm using Ubuntu.

**Comment by bitti** [comment]
You're right, I only tested on MacOS :( It seems the pipes life longer there, but that might also not be reliable... In this case I'm afraid it will be difficult to come close to the proposed syntax. The easiest would be to just inline the process substitutions:

     q -H -t "select b.c1,a.name,b.c2 from ~/author.tsv a join "<(cat dummy-header.tsv editor.tsv)" b on a.ID=b.c1"

If that is not acceptable but your files are not that big you could also just use temporary files. If your files are so big that prepending a header would incur significant costs, you could also use named pipes, e.g.:

    mkfifo b
    cat dummy-header.tsv editor.tsv >b &
    q -H -t "select b.c1,a.name,b.c2 from ~/author.tsv a join b on a.ID=b.c1"
    rm b

At this point it might be worth to use some kind of wrapper script or function though.

**Comment by wtanksleyjr** [comment]
Well, at least we have a clear workaround and an understanding of the complexities. Thanks for the help!

As a minor comment to anyone who reads later, putting "~/author.tsv" inside a string won't work in Bash. You have to either put it outside the string, or use "$HOME" instead of "~/". It's just how bash works.

**Comment by bitti** [comment]
Yes bash can make the substitution for `~`, but not `q` itself. That's certainly not a bug since it's just a shell feature. But I also noticed that I have to use an alias for `b` (i.e. `b b`) or the headers won't be parsed correctly (`query error: no such column: b.c1`). @harelba: maybe that's a bug, or is it supposed to work that way?

**Comment by wtanksleyjr** [comment]
It kind of makes sense; complex filenames won't be legal table names
anyhow. I always make aliases, except when I'm using only one table and so
don't need any dotted qualifiers.
