### ISSUE TITLE
Q doesnot list the value correctly

### ISSUE THREAD

**Issue by rajkirandav** [harelba/q#208]
Hi ,I have the file content as below 
01022517359362791112131139
01022517359362791112131139

When i try to list using q ,the o/p comes in exponent form as below 
[wdbs@bt-pcrf-app1 ~]$  q "select c1 from 1"|head
Warning: column count is one - did you provide the correct delimiter?
1.02251735936e+24
1.02251735936e+24

Basically i would like to retain the q o/p in the same format as in the source file .Any suggestion pls

**Comment by bitti** [comment]
Use the `--as-text` option when you don't have any columns which need numeric interpretation.

**Comment by rajkirandav** [comment]
Thanks Mate..
