### ISSUE TITLE
2.0.9 build fails - no releases

### ISSUE THREAD

**Issue by MCOfficer** [harelba/q#216]
Apparently Travis failed to build releases for 2.0.9, as a result nothing can be downloaded:

https://travis-ci.org/harelba/q/builds/636002923

I'm just filing this in case you didn't notice. Feel free to close it.

**Comment by MCOfficer** [comment]
Apparently this has been fixed

**Comment by harelba** [comment]
Hi, this was related to the new packaging flow. 2.0.9 is already released, you can download it from the q website [here](http://harelba.github.io/q/)
