### ISSUE TITLE
cannot use in Windows 10

### ISSUE THREAD

**Issue by sesameguy** [harelba/q#224]
OS: Windows 10 64 bit
Version: 1909

cannot use the program, it show the below error message:
``
INTERNAL ERROR: cannot create temporary directory!
``

**Comment by harelba** [comment]
can't reproduce it on my (only) windows machine.

Can you go to the command line and run `echo %TEMP%`. Also try to create a file in this folder, to make sure it's not a permission issue.

**Comment by sesameguy** [comment]
thx, the problem is fixed.
it is because the %TEMP% is placed in ramdisk
