### ISSUE TITLE
Can't change encoding

### ISSUE THREAD

**Issue by asgerhallas** [harelba/q#226]
Hi, 

On windows, q v2.0.9, no matter which encoding I use except for "utf-8", I get this message:

`AttributeError("'UnicodeDecodeError' object has no attribute 'message'")`

or for some encodings...

`AttributeError("'UnicodeError' object has no attribute 'message'")`

For example when I do this: 

`q -tH -e "ascii" "SELECT * FROM data.tsv WHERE titleType = 'movie'"`

What am I doing wrong? :)

**Comment by harelba** [comment]
hi, sorry for the too-late reply, crazy times

could you please provide some more information about your system, and perhaps an example file (just the first few lines, or a synthetic file which recreates the issue) so i can investigate?

**Comment by christophgysin** [comment]
Here's an example:

```
$ echo -e "\xe6" > test.csv
$ q "SELECT * FROM test.csv"
AttributeError("'UnicodeDecodeError' object has no attribute 'message'")
```

**Comment by asgerhallas** [comment]
(@harelba sorry for my late reply too. I missed yours it seems, but @christophgysin's message got me in here again)

**Comment by harelba** [comment]
This character is on the upper half of ASCII, and the standard ascii encoding in python doesn't support that other half.

Use the `iso-8859-1` encoding, it's kind of an extended ASCII which supports the upper half of the characters.

```
$ q -e iso-8859-1 "SELECT * FROM test.csv"
Warning: column count is one - did you provide the correct delimiter?
æ
$
```
