### ISSUE TITLE
Windows installation wipes user path

### ISSUE THREAD

**Issue by mosheduminer** [harelba/q#238]
I installed `q` last night on my windows 10 laptop, and it was really cool. This morning, however, I discovered my user path wiped, with only `q` in the path. This is a significant problem for (and will probably not be appreciated by) anyone using windows.

**Comment by harelba** [comment]
The path issue is very odd, as 30% of q's installations are on windows and I've never heard about this before, and the issue doesn't happen on 2 windows 10 machines I've tested it with.

I've just released a new version `2.0.16`. It would be awesome if you can check it out and see if the problem happens again.

Thanks for reporting this
Harel

**Comment by mosheduminer** [comment]
The path remains unaltered (aside from adding q to the path again), when I install the new version. I agree, it does seem rather odd. Thank you for looking into this. 🙂

**Comment by harelba** [comment]
Thanks for the reply, i'm glad it helps.

If this happens again, don't hesitate to reopen the ticket.
