### ISSUE TITLE
Running "q" fails with "ImportError: No module named six.moves"

### ISSUE THREAD

**Issue by workflowsguy** [harelba/q#239]
Installed `q` with `brew install q` -> installs version 2.0.11

Running `q` fails with
```
Traceback (most recent call last):
  File "/usr/local/bin/q", line 48, in <module>
    from six.moves import configparser, range, filter
ImportError: No module named six.moves
```

Running `pip list` shows

`six                                    1.15.0`

**Comment by harelba** [comment]
Thanks for reporting this. It's an bug in the brew formula for the new version of q. I am planning to fix it soon.

Can you please try to install one of the older versions of q through brew by running "brew install q@1.7.4" or "brew intall q@1.7.1" and tell me if works or not?

I'll try to properly fix it as soon as possible.

Really sorry for the inconvenience

Harel

**Comment by workflowsguy** [comment]
> Can you please try to install one of the older versions of q through brew by running "brew install q@1.7.4" or "brew install q@1.7.1" and tell me if works or not?

Unfortunately, trying to install either one of those results in an error:
```
Error: No available formula with the name "q@1.7.4" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

> I'll try to properly fix it as soon as possible.

Thanks!

**Comment by harelba** [comment]
Thanks, I'm working on the solution. I'll update here when done

**Comment by harelba** [comment]
PR in homebrew with a proper fix. Hopefully will be approved soon - https://github.com/Homebrew/homebrew-core/pull/60861

**Comment by harelba** [comment]
PR in homebrew merged.

`brew install q` works properly now (version `2.0.16`). Run `brew uninstall q` and then install again.

Please let me know if you have any issues.

Thanks for reporting this and for the patience.

Harel

**Comment by workflowsguy** [comment]
My preliminary tests show that it is working again.

Thanks!
