### ISSUE TITLE
virustotal: Warnings related to q-x86_64-Linux  for version 2.0.19

### ISSUE THREAD

**Issue by uli-heller** [harelba/q#243]
I downloaded version 2.0.19
and fed it into virustotal.
I'm getting these:

![image](https://user-images.githubusercontent.com/1677414/94780602-01e49700-03c9-11eb-8e42-0730c607f082.png)

Do I have to be concerned?

Thx, uli

**Comment by uli-heller** [comment]
I'm getting the same warnings for older versions, too

**Comment by harelba** [comment]
@uli-heller thanks for reporting this. 

There's definitely no need to be concerned :) The source code is fully open and q doesn't even access the network at all. Perhaps it's related to pyinstaller's way of packaging.

I'll take a deeper look at it to see how these warning can be eliminated.

**Comment by harelba** [comment]
New version of q is out, packaged with pyoxidizer. Tested all artifacts on virustotal - No issues at all.

Screenshots:

![Screen Shot 2021-12-02 at 11 34 53](https://user-images.githubusercontent.com/985765/144395715-cd37a13b-d425-4a2c-9071-d7a9839afe44.png)
![Screen Shot 2021-12-02 at 11 35 21](https://user-images.githubusercontent.com/985765/144395768-9d3c80d6-8357-471f-abcb-6c8c2beed496.png)
![Screen Shot 2021-12-02 at 11 35 36](https://user-images.githubusercontent.com/985765/144395805-14844ac3-fd64-4821-9bac-62fc746f6dbe.png)
![Screen Shot 2021-12-02 at 11 35 56](https://user-images.githubusercontent.com/985765/144395879-54851b94-7f25-48a6-81c6-530d2203fdaa.png)
![Screen Shot 2021-12-02 at 11 36 16](https://user-images.githubusercontent.com/985765/144395924-62a86f92-48bc-4647-89e5-30b442c87b42.png)
![Screen Shot 2021-12-02 at 11 36 52](https://user-images.githubusercontent.com/985765/144396028-fd369800-9368-459d-be06-e9f0394eda6b.png)
