### ISSUE TITLE
query error: no such table:

### ISSUE THREAD

**Issue by Dialga** [harelba/q#247]
`select * from file.csv` works but
`select*from file.csv` doesn't work, which works in sqlite.

**Comment by harelba** [comment]
true, and interesting. I'll do some testing.

**Comment by harelba** [comment]
This is a limitation because of the way q parses the sql queries (It expects a space before the FROM part). 

This would work:
```
q "select* from aaa"
```

There are no plans to fix this, as this is very complicated relative to the gain.
