### ISSUE TITLE
version requirements for six should be consistent?

### ISSUE THREAD

**Issue by suliuzh** [harelba/q#258]
Hi
It seems that version requirements for six in setup.py and mkdocs/requirements.txt are not consistent
In setup.py, it is six==1.11.0
In mkdocs/requirements.txt, it is six==1.14.0

I am wondering if it is necessary to update the version requirement in 'mkdocs/requirements.txt' to be consistent.

**Comment by harelba** [comment]
the mkdocs folder is isolated from the q runtime, it's just used for generating q's web site, so there's no need for consistency.
