### ISSUE TITLE
Is wrapt a unused dependency?

### ISSUE THREAD

**Issue by yuluc1234** [harelba/q#266]
Hi
There seems to be no code in the source code that uses the dependency- wrapt, is it necessary for the project to work? 

But in mkdocs/requirements.txt, wrapt is still listed as a pinned dependency. 

So should wrapt remove from the configuration file?

**Comment by harelba** [comment]
Hi,

The requirements in `mkdocs/` contains dependencies that are needed in order to generate q's site, they're not packaged with q itself.
