### ISSUE TITLE
How to use NOT LIKE in query?

### ISSUE THREAD

**Issue by Pantos** [harelba/q#268]
I'm very happy to find q to query my csv files. But how can I use NOT LIKE in a query? At the moment it doesn't seem to affect my results when I put it in the WHERE clause. Can anyone give me a hint?

**Comment by harelba** [comment]
```
$ seq 1 100 | qq "select * from - where c1 like '%55%'"  | wc -l
1
$ seq 1 100 | qq "select * from - where c1 not like '%55%'"  | wc -l
99
```

Hope that helps.

Btw, if you're in windows, then the `%` signs have special meanings, perhaps you'd need to escape them.
