### ISSUE TITLE
Can we support more glibc version ?

### ISSUE THREAD

**Issue by coderpolo** [harelba/q#297]
want use cache feature on old centos 6.2 with glibc like 2.12.
 
I had test q(3.1.6) with glibc 2.17 on CentOS 7.8. It works fine.
so i have to scp file to the machine with  glibc 2.17 serval times a day.

**Comment by harelba** [comment]
Sorry, the limitation of glibc version is related to the packaging process of q (a pyoxidizer limitation). I wanted to provide support for a lower glibc version but it's not possible with pyoxidizer.
