### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by kannan83** [harelba/q#34]
hi, 

a very nice project. :+1: 

by the way, i have a question: is this project same as https://github.com/dinedal/textql ??

**Comment by mikaello** [comment]
Do you have any plans to publish the comparison between textql and q? That would be very interesting to see :-)

**Comment by harelba** [comment]
I'd have to say that I have not saved any of the results of the comparison i did a long while ago.

Perhaps I'll do another comparison at some point and publish it.
