### ISSUE TITLE
Feature request: process substitution

### ISSUE THREAD

**Issue by vi** [harelba/q#67]
Something like `q "SELECT * FROM <(find . -ls)"`

It should be like

```
mkfifo tmptable
find . -ls > tmptable&
q "SELECT * FROM tmptable"
```

**Comment by chancez** [comment]
is it possible there could be support added to allow something like this?
```
q -O -d ' ' -H --table kube_pods=<(kubectl get pods -o wide | gsed -E -e '1s/(\w)\s(\w)/\1_\2/g') --table top_pods=<(k top pods | sed -e '1s/(/_/g' -e '1s/)//g' -e 's/[ \t]*$//') 'SELECT * FROM kube_pods JOIN top_pods ON kube_pods.NAME=top_pods.NAME ORDER BY CPU_cores DESC LIMIT 5'
```

Basically adding the ability to specify table names for each file, and reference those in the query. I have some complex commands I'd like to use, but don't want to have to deal with quoting/unquoting/etc, and I don't want to use a temporary file since it complicates it a bit.

**Comment by bitti** [comment]
> I have some complex commands I'd like to use, but don't want to have to deal with quoting/unquoting/etc, and I don't want to use a temporary file since it complicates it a bit.

There shouldn't be any quoting issues, just put the process substitutions outside of quotes. I.e.

```
q -O -d ' ' -H 'SELECT * FROM '<(kubectl get pods -o wide | gsed -E -e '1s/(\w)\s(\w)/\1_\2/g')' kube_pods JOIN '<(k top pods | sed -e '1s/(/_/g' -e '1s/)//g' -e 's/[ \t]*$//')' top_pods ON kube_pods.NAME=top_pods.NAME ORDER BY CPU_cores DESC LIMIT 5'
```

**Comment by chancez** [comment]
> > I have some complex commands I'd like to use, but don't want to have to deal with quoting/unquoting/etc, and I don't want to use a temporary file since it complicates it a bit.
> 
> There shouldn't be any quoting issues, just put the process substitutions outside of quotes. I.e.
> 
> ```
> q -O -d ' ' -H 'SELECT * FROM '<(kubectl get pods -o wide | gsed -E -e '1s/(\w)\s(\w)/\1_\2/g')' kube_pods JOIN '<(k top pods | sed -e '1s/(/_/g' -e '1s/)//g' -e 's/[ \t]*$//')' top_pods ON kube_pods.NAME=top_pods.NAME ORDER BY CPU_cores DESC LIMIT 5'
> ```

Right, I guess I just meant having to even worry about where to position the command substitution/etc. It also just makes the query really hard to understand. Being able to separate out the files from the query would be very useful.

**Comment by chancez** [comment]
Somewhat similar to #203 as well

**Comment by bitti** [comment]
> Being able to separate out the files from the query would be very useful.
> Somewhat similar to #203 as well

I understand that and my suggestion back then to assign the file descriptors to shell variables wasn't very good due to race conditions. But you can just use shell functions, e.g.:

```
kube_pods()(kubectl get pods -o wide | gsed -E -e '1s/(\w)\s(\w)/\1_\2/g'); top_pods()(k top pods | sed -e '1s/(/_/g' -e '1s/)//g' -e 's/[ \t]*$//'); q -O -d ' ' -H 'SELECT * FROM '<(kube_pods)' kube_pods JOIN '<(top_pods)' top_pods ON kube_pods.NAME=top_pods.NAME ORDER BY CPU_cores DESC LIMIT 5'
```

Granted it has a tad more repetition than when it would be an option, but shell functions are also more reusable and we've one less option to remember.

**Comment by chancez** [comment]
The shell functions change basically between each invocation depending on what I'm looking at :\

**Comment by bitti** [comment]
> The shell functions change basically between each invocation depending on what I'm looking at :\

Then you can just edit the line as you would with an option. But I suppose even then you'd like to test these substitutions separately where having them as a function might come in handy.

**Comment by chancez** [comment]
Even without shell commands involved, what do you think of the idea of a `--table` flag or something like I suggested?

**Comment by bitti** [comment]
I'm not sure if your question is just for @harelba for the general public. In case it's the latter I'd say: I wonder what your use-case for this flag is if there shouldn't be shell commands involved, considering that your example uses process substitutions which are a shell feature?

**Comment by chancez** [comment]
Without process substitutions it would just be a method of supplying files with a specific table name

**Comment by harelba** [comment]
hi people, sorry for the late reply, i was unable to be online for a while.

Thank you all for the comments and involvement on this.

adding support for "virtual table names" such as  the `--table x=<(cmd)` example above would be easily possible after i release the new version (in fact, '-' as stdin is implemented in a very similar manner internally). If that would help to make things easier for some use cases, then it might be a good idea to add it.

I'll consider adding it later on it, after i release the coming major version.

**Comment by vi** [comment]
Maybe a workaround for #124 can be added as well, to mark specific tables as defined from within SQL query, inhibiting `q`'s processing?
Like in [my workaround](https://github.com/harelba/q/issues/124#issuecomment-585172056), but triggered by command line instead of special table name.
