### ISSUE TITLE
"no such column" error even when the column exists

### ISSUE THREAD

**Issue by iambibhas** [harelba/q#90]
This is an example of the data and the problem - 

    ╭─ ツ /mnt/Works/klp/www/www_csvs 10:03AM ‹›
    ╰─$ ./q "select * from tb_school.csv limit 10";                                       
    inst_id,boundary_id,inst_address_id,dise_code,inst_name,inst_category,institution_gender,moi,management,active    
    29884,963,136131,,GLPS HARSOOR TANDA,Lower Primary,co-ed,,ed,2 
    29566,8808,135433,AN0065,GOWRENAHALLI A,Anganwadi,co-ed,,ed,2   
    29572,8817,135439,AN0071,KONADASAPURA2,Anganwadi,co-ed,,ed,2    
    31322,8863,180615,AN001482,KONDASHETTIHALLI,Anganwadi,co-ed,,ed,2    
    29584,8822,,AN0083,AHAREHALLI,Anganwadi,co-ed,kannada,ed,2    
    29592,8816,135459,AN0091,INDIRANAGAR11,Anganwadi,co-ed,,ed,2    
    37261,8871,249072,"",SUNNAVARA 1,Anganwadi,co-ed,kannada,ed,2   
    29607,8826,135474,AN00142,BADAMAKAAN I,Anganwadi,co-ed,,ed,2   
    29612,8829,135479,AN00147,CHRISTIAN COLONY,Anganwadi,co-ed,,ed,2   
    ╭─ ツ /mnt/Works/klp/www/www_csvs 10:04AM ‹›
    ╰─$ ./q "select inst_address_id from tb_school.csv limit 10";                         
    query error: no such column: inst_address_id

The first query shows that the `inst_address_id` column is in the file and yet the query is throwing the error. Am I missing something?

**Comment by harelba** [comment]
Hi, you need to use `-H` in order to tell q that there is a header row, and also use `-d ,` to signify that that delimiter is a comma. 

Please tell me if things still don't work for some reason.

**Comment by iambibhas** [comment]
Ah. That works. Thanks @harelba.

**Comment by sryze** [comment]
@harelba Could you please add those flags to the usage examples in `--help` message? I think it's pretty common to have a header and use comma as a delimiter that  itdeserves to be mentioned.

**Comment by harelba** [comment]
yes, i'll add them, you're right.
